---
title: "README"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{README}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

#Objective

The purpose of this assessment is for you to combine your skills of creating, writing, documenting, and testing an R package with releasing that package on GitHub. In this assessment you'll be taking the R files from Week 2's assessment about documentation and putting that file in an R package.

For this assessment you must

1.write a vignette to include in your package using knitr and R Markdown
2.write at least one test written using testthat
3.put your package on GitHub
4.set up the repository so that the package can be checked and built on Travis
5.Once your package has built on Travis and the build is passing with no errors, warnings, or notes you should
6. add your Travis badge to the README.md file of your package repository.

# US FARS (Fatality Analysis Recording System)

This package sole objective is to produce graphics of the accidents in US.

## The `make_filename` function

This function generates a filename.

## The `fars_read` function

The `fars_read` will use as input the filename string from `make_filename`.

Based on the archives from US FARS that are located in the documents folder.

## The `fars_read_years` function

This functions uses both functions (`make_filename` and `fars_read`) to generate a list.

## The `fars_summarize_years` function

This functions print a summary.

## The `fars_map_state` function

Plot a Graphic of each State of US.

# Dependencies

* dplyr
* magrittr
* tidyr
* rlang
* graphics
* maps
